### ISSUE TITLE
Even also after adding Authorization hederwith token, i am getting "Authentication credentials were not provided"

### ISSUE THREAD

**Issue by suraj13k** [srijannnd/mango-jwt#1]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mongo_auth'
]

**Comment by srijannnd** [comment]
Looks like you are trying yo connect to MongoDB Atlas. Don't include "db_port" if this is the case and use srv host in "db_host". Upgrade to the latest version and read the docs. They have been updated.
