### ISSUE TITLE
"Authentication failed" when trying to sign up.

### ISSUE THREAD

**Issue by StefanSympax** [srijannnd/mango-jwt#2]
![image](https://user-images.githubusercontent.com/16557115/55507239-80873980-5657-11e9-9521-2c5f71080e2a.png)

with this simple code (following yout instructions) i get that error and i can't find out what happens...any idea?

**Comment by srijannnd** [comment]
Added support for MongoDB Atlas as well. Kindly upgrade to the latest version and you will be good to go.
