### ISSUE TITLE
Feature request: Add Authentication Source

### ISSUE THREAD

**Issue by Zuiluj** [srijannnd/mango-jwt#4]
I would like to request a feature where you can specify the authentication source for the mongodb. Most dev creates mongodb 'user' in admin, what happens is: mango-jwt looks for the user in the specified database ONLY, so it throws an authentication error:

`UserNotFound: Could not find user "root" for db "custom_db"`

**Comment by srijannnd** [comment]
No need. I added support for MongoDB Atlas. You just need to add new srv host in "db_host" now. Upgrade to the latest version and you will be good to go.
